FLASK_APP='manage.py'
FLASK_DEBUG=1
FLASK_ENV=development
SECRET_KEY='you-will-never-guess'
DB_USERNAME=peefer66
DB_PASSWORD=aWBiM02
DB_HOST=localhost
DATABASE_NAME=jacques
MYSQL_ROOT_PASSWORD=aWBiM02
APP_NAME='Jacques Products'