"""empty message

Revision ID: 388377d6adbf
Revises: 4e91b4337ae9
Create Date: 2019-02-24 19:26:21.230501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388377d6adbf'
down_revision = '4e91b4337ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpd_no', sa.String(length=25), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.Column('date_issued', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpd_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compound')
    # ### end Alembic commands ###
