"""empty message

Revision ID: 59b5ed9d7efb
Revises: 218122ae5fd9
Create Date: 2019-02-25 19:26:45.404280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b5ed9d7efb'
down_revision = '218122ae5fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compound', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'compound', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'compound', type_='foreignkey')
    op.drop_column('compound', 'customer_id')
    # ### end Alembic commands ###
