"""empty message

Revision ID: a3368e7ae169
Revises: fafa36395069
Create Date: 2019-03-02 14:10:26.857017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3368e7ae169'
down_revision = 'fafa36395069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=25), nullable=True))
    # ### end Alembic commands ###
